### ISSUE TITLE
Initial Events not completely covering the viewport

### ISSUE THREAD

**Issue by ketanhwr** [sdslabs/portfolio#15]
In my resolution (1920 x 1080), only 2 initial events are being displayed, which do not cover the screen completely and therefore it looks odd.

I believe, that number of initial achievements which are visible, should depend on the resolution.

![Screenshot](https://image.ibb.co/f4FrrF/Screenshot_from_2017_03_22_15_01_28.png "Screenshot")

**Comment by ayanchoudhary** [comment]
Closing due to deprecation of old portfolio
